name = "5266-bp-app"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "bp-app-db"
database_id = "07a4f37d-d04d-406d-ac5c-c71a59eba141"
