name = "5266-bp-app-v20"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "5266-bp-app-v20"
database_id = "fdb6ce2a-65b7-4377-83ba-611089352f80"
